spring:
    application:
        name: hms
    datasource:
        url: jdbc:postgresql://localhost:5432/databaseHms
        username: userHms
        password: hms123
        driver-class-name: org.postgresql.Driver
        hikari:
            jdbc-url: jdbc:postgresql://localhost:5432/databaseHms
            driver-class-name: org.postgresql.Driver

