spring:
    application:
        name: hms
    datasource:
        url: jdbc:postgresql://localhost:5432/databaseHms
        username: userHms
        password: $password
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://localhost:5432/databaseHms

