spring:
    jpa:
      hibernate:
        ddl-auto: create
    application:
        name: hms
    datasource:
        url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            jdbc-url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
            driver-class-name: org.postgresql.Driver
server:
    port: "${port:8080}"
